name: Run Notebook Daily

on:
  schedule:
    # Schedule: 8:00 AM GMT+1 (Europe/Paris)
    - cron: '29 13 * * *'

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install notebook nbconvert

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute --inplace MDA.ipynb
